version: "3.4"

services:
  oauth-client:
    container_name: dev-rs-oauth-client
    image: php:apache
    working_dir: /var/www/html
    volumes:
      - ./oauth-client:/var/www/html
    ports:
      - 7071:80